In [16]:
import pandas as pd
# Asked ChatGPT to give me some exercises based on DataFrame basics #

In [17]:
# First exercise
df = pd.DataFrame({
    "name" : ['Anna', 'Ivan', 'Olga', 'Petr'],
    "age" : [23, 30, 27, 35],
    "city" : ["Moscow", "Kazan", "Moscow", "Samara"]
})
print(df, "\n\n")

print("First task:\n", df.head(3), '\n\n') # 1

print("Second task:\n", df[ df["age"] > 25], '\n\n') # 2

print("Thrird task:\n Средний возраст опрошенных равен ", df["age"].mean())

   name  age    city
0  Anna   23  Moscow
1  Ivan   30   Kazan
2  Olga   27  Moscow
3  Petr   35  Samara


First task:
    name  age    city
0  Anna   23  Moscow
1  Ivan   30   Kazan
2  Olga   27  Moscow


Second task:
    name  age    city
1  Ivan   30   Kazan
2  Olga   27  Moscow
3  Petr   35  Samara


Thrird task:
 Средний возраст опрошенных равен  28.75

In [31]:
# Second exercise
print(df[["name", "age"]], '\n\n') # 1

#print(df["age"].sort_values(), '\n\n') # 2 - not quite what was needed, but okay
print(df.sort_values("age"), '\n\n')

print(f'Max age is {df["age"].max()}. And the minimum age is {df["age"].min()}.')

   name  age
0  Anna   23
1  Ivan   30
2  Olga   27
3  Petr   35


   name  age    city
0  Anna   23  Moscow
2  Olga   27  Moscow
1  Ivan   30   Kazan
3  Petr   35  Samara


Max age is 35. And the minimum age is 23.

In [30]:
# Third exercise
print(df[ df['city'] == 'Moscow']) # 1

mean_age = df['age'].mean()
print(mean_age)
#print( df[ (df['city'] == 'Moscow') & ( df['age'] > df['age'].mean() ) ] ) - prototype
print( df[ (df['city'] == 'Moscow') & ( df['age'] > mean_age ) ] )

   name  age    city
0  Anna   23  Moscow
2  Olga   27  Moscow
28.75
Empty DataFrame
Columns: [name, age, city]
Index: []

In [33]:
df['age'] #method display() is automatically prints one last string

0    23
1    30
2    27
3    35
Name: age, dtype: int64

In [35]:
# How to display multilple things?
from IPython.display import display

display(df)
display(df.head(2))

   name  age    city
0  Anna   23  Moscow
1  Ivan   30   Kazan
2  Olga   27  Moscow
3  Petr   35  Samara

   name  age    city
0  Anna   23  Moscow
1  Ivan   30   Kazan